"""Measured secret redactor (task-2-brief.md, gate G1.7; fix round 1).

`redact_detail(text)` replaces each detected secret span with
`[REDACTED:<rule_id>]` and returns the tuple of rule ids that fired, in the
order their spans appear. `redact(text)` is built on it and returns the hit
count instead of the rule ids. Rules come from `_redact_rules.RULES`
(generated by `scripts/gen_redact.py` from vendor/gitleaks.toml plus local
rules); local-rule false positives are additionally filtered by
`_redact_filters` (fix round 1, item 2).

Startup cost matters: importing this module compiles nothing. Each rule's
pattern is a plain string until its keyword is first seen in scanned text,
at which point it is compiled once and cached in `_PATTERN_CACHE` for the
life of the process.

Catastrophic-backtracking guard: text is processed in overlapping windows of
`_WINDOW_SIZE` characters (`_WINDOW_OVERLAP` overlap -- at least as large as
any realistic secret span, including a multi-KB PEM block) rather than
handed to the regexes whole, so a pathologically large payload cannot blow
up a single regex call. Every window up to the end of the text is scanned
(no suffix is ever dropped), and hits found in the overlap region are
identical (same absolute span, same rule) in both windows and are
deduplicated by that span before the text is rebuilt, so nothing is
redacted twice.

A rule's secret is the union of every *participating* capturing group in a
match (an alternation rule where only one branch matches per attempt), or
the whole match when no group participated (fix round 1, item 4) -- picking
a single fixed group index would silently drop secrets captured by a later
group.

Failure is explicit (fix round 1, item 3; global-constraints.md "a redactor
exception means the text field is replaced, never written raw"): any
unexpected internal exception makes `redact_detail` return
`("[redaction failed]", ())` and `redact` return `("[redaction failed]",
-1)`, rather than silently returning the un-redacted input.
"""

from __future__ import annotations

import math
import os
import re
from collections import Counter

from . import _redact_filters, _redact_rules

_PATTERN_CACHE: dict[str, re.Pattern[str]] = {}
_ALLOWLIST_CACHE: list[re.Pattern[str]] | None = None

_WINDOW_SIZE = 64 * 1024
_WINDOW_OVERLAP = 8192
# Short lookback for adjacency-only cue checks (fix round 2, item 2): must
# only be as long as the longest fixed cue string ("sk-ssh-ed25519@openssh
# .com " is 28 chars), never large enough to see a cue word elsewhere on
# the line -- that was the false-negative bug this round fixes.
_CONTEXT_LOOKBACK = 32
# Much larger lookback used only to find an enclosing PEM
# public-key/certificate block header (fix round 2, item 4): those blocks
# can be a few KB.
_PEM_LOOKBACK = 4096
# Rule ids that say only "this looked like a secret", with no family
# attribution (fix round 4, finding 4).
_GENERIC_RULE_ID = "generic-api-key"
_ENTROPY_RULE_PREFIX = "local-high-entropy-"
_REDACTED_MARKER_PREFIX = "[REDACTED:"
_MARKER_TEMPLATE = _REDACTED_MARKER_PREFIX + "{}]"
_FAILURE_MARKER = "[redaction failed]"


def _compiled_pattern(rule_id: str, pattern: str) -> re.Pattern[str]:
    compiled = _PATTERN_CACHE.get(rule_id)
    if compiled is None:
        compiled = re.compile(pattern)
        _PATTERN_CACHE[rule_id] = compiled
    return compiled


def _allowlist_patterns() -> list[re.Pattern[str]]:
    global _ALLOWLIST_CACHE
    if _ALLOWLIST_CACHE is None:
        _ALLOWLIST_CACHE = [re.compile(p) for p in _redact_rules.ALLOWLIST_REGEXES]
    return _ALLOWLIST_CACHE


def _shannon_entropy(value: str) -> float:
    if not value:
        return 0.0
    length = len(value)
    counts = Counter(value)
    return -sum((n / length) * math.log2(n / length) for n in counts.values())


def _is_allowlisted(secret: str) -> bool:
    lowered = secret.lower()
    if any(stopword.lower() in lowered for stopword in _redact_rules.STOPWORDS):
        return True
    return any(pattern.fullmatch(secret) for pattern in _allowlist_patterns())


def _match_spans(match: re.Match[str]) -> list[tuple[int, int]]:
    """Every participating capturing group's span, or the whole match.

    A vendored alternation rule (e.g. a curl Authorization-header rule with
    one capturing group per auth style) only ever has ONE of its several
    groups participate per match; picking a single fixed group index would
    miss the secret whenever a different branch fired (fix round 1, item 4).
    """
    total_groups = match.re.groups
    if total_groups == 0:
        return [match.span(0)]
    spans = [match.span(i) for i in range(1, total_groups + 1) if match.span(i) != (-1, -1)]
    return spans if spans else [match.span(0)]


def _candidate_hit(
    window: str, start: int, end: int, rule_id: str, entropy_floor: float | None
) -> bool:
    if start == end:
        return False
    secret = window[start:end]
    if _REDACTED_MARKER_PREFIX in secret:
        return False  # idempotency: never re-redact our own marker text
    if entropy_floor is not None and not (_shannon_entropy(secret) > entropy_floor):
        return False
    if _is_allowlisted(secret):
        return False
    preceding = window[max(0, start - _CONTEXT_LOOKBACK) : start]
    pem_context = window[max(0, start - _PEM_LOOKBACK) : start]
    return _redact_filters.passes_local_filters(rule_id, secret, preceding, pem_context)


def _rule_hits(window: str, lowered_window: str) -> list[tuple[int, int, str]]:
    hits: list[tuple[int, int, str]] = []
    for rule_id, pattern, keywords, entropy_floor in _redact_rules.RULES:
        if keywords and not any(keyword in lowered_window for keyword in keywords):
            continue
        try:
            compiled = _compiled_pattern(rule_id, pattern)
            for match in compiled.finditer(window):
                for start, end in _match_spans(match):
                    if _candidate_hit(window, start, end, rule_id, entropy_floor):
                        hits.append((start, end, rule_id))
        except re.error:
            continue
    return hits


def _windows(text: str) -> list[tuple[int, str]]:
    length = len(text)
    if length <= _WINDOW_SIZE:
        return [(0, text)]
    windows: list[tuple[int, str]] = []
    start = 0
    while True:
        end = min(length, start + _WINDOW_SIZE)
        windows.append((start, text[start:end]))
        if end >= length:
            return windows
        start = end - _WINDOW_OVERLAP


def _is_generic_rule(rule_id: str) -> bool:
    return rule_id == _GENERIC_RULE_ID or rule_id.startswith(_ENTROPY_RULE_PREFIX)


def _attribute(spans: set[tuple[int, int, str]]) -> list[tuple[int, int, str]]:
    """One rule id per span, preferring a non-generic rule (fix round 4,
    finding 4).

    A span matched by both a vendor rule and a generic one used to be
    credited alphabetically, so `generic-api-key` beat `openai-api-key` on
    the identical span and non-generic recall was understated. Ties among
    non-generic (or among generic) ids stay alphabetical, so attribution
    remains deterministic.
    """
    best: dict[tuple[int, int], str] = {}
    for start, end, rule_id in spans:
        current = best.get((start, end))
        if current is None or (_is_generic_rule(current), current) > (
            _is_generic_rule(rule_id),
            rule_id,
        ):
            best[(start, end)] = rule_id
    return sorted((start, end, rule_id) for (start, end), rule_id in best.items())


_ENV_RULE_ID = "env-configured-secret"
_ENV_SECRET_PREFIX = "CLAUDE_PLUGIN_OPTION_"
_ENV_SECRET_EXACT_NAMES = frozenset({"OPENROUTER_API_KEY", "TYPESAFE_API_KEY", "ANTHROPIC_API_KEY"})
_MIN_ENV_SECRET_LEN = 8


def _env_secret_values() -> tuple[str, ...]:
    """Values of this process's own configured secrets, whatever their format.

    A key the user configured for the plugin, or a provider key in the
    environment, must never reach the ledger even when no pattern rule
    recognizes its shape (an echoed key is the most likely leak path).
    """
    values = []
    for name, value in os.environ.items():
        is_secret_name = name.startswith(_ENV_SECRET_PREFIX) or name in _ENV_SECRET_EXACT_NAMES
        if is_secret_name and value and len(value) >= _MIN_ENV_SECRET_LEN:
            values.append(value)
    return tuple(sorted(values, key=len, reverse=True))


def _env_value_spans(text: str) -> set[tuple[int, int, str]]:
    spans: set[tuple[int, int, str]] = set()
    for value in _env_secret_values():
        start = text.find(value)
        while start != -1:
            spans.add((start, start + len(value), _ENV_RULE_ID))
            start = text.find(value, start + len(value))
    return spans


def _redact_unsafe(text: str) -> tuple[str, tuple[str, ...]]:
    spans: set[tuple[int, int, str]] = _env_value_spans(text)
    for offset, window in _windows(text):
        lowered = window.lower()
        for start, end, rule_id in _rule_hits(window, lowered):
            spans.add((offset + start, offset + end, rule_id))
    if not spans:
        return text, ()

    parts: list[str] = []
    rule_ids: list[str] = []
    cursor = 0
    for start, end, rule_id in _attribute(spans):
        if start < cursor:
            continue  # overlaps a span already accepted; keep the earlier one
        parts.append(text[cursor:start])
        parts.append(_MARKER_TEMPLATE.format(rule_id))
        rule_ids.append(rule_id)
        cursor = end
    parts.append(text[cursor:])
    return "".join(parts), tuple(rule_ids)


def redact_detail(text: str) -> tuple[str, tuple[str, ...]]:
    try:
        return _redact_unsafe(text)
    except Exception:  # noqa: BLE001 - failure must be explicit, never raise
        return _FAILURE_MARKER, ()


def redact(text: str) -> tuple[str, int]:
    try:
        cleaned, rule_ids = _redact_unsafe(text)
        return cleaned, len(rule_ids)
    except Exception:  # noqa: BLE001 - failure must be explicit, never raise
        return _FAILURE_MARKER, -1
