"""Gate G1.7 (task-2-brief.md; fix round 1): redaction recall and FPR.

Recall = fraction of positives whose `secret` no longer appears verbatim in
the redacted output. False-positive rate = fraction of negatives (secret is
null) that get any hit at all. The corpus (tests/fixtures/secrets_corpus.jsonl)
is generated by `python3 scripts/gen_redact.py --corpus`
(scripts/gen_corpus.py) and must never be hand-tuned to make these numbers
look better than they are.

Fix round 1 adds two things a held-out reviewer probe found missing:
- Every row records which context produced it and whether that context is
  "bare" (no adjacent key/token/secret label). The gate additionally reports
  bare-context recall per family.
- For the 15 "structured" families (real dedicated rules exist for their
  format), bare-context positives must be redacted by a rule that is NOT
  `generic-api-key` or one of the `local-high-entropy-*` catch-alls -- i.e.
  the family's own rule, not a keyword-adjacency fallback that only works
  because the corpus happened to label the secret.
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "plugin" / "hooks"))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
from gen_corpus import STRUCTURED_FAMILIES  # noqa: E402
from verdict_hot import redact  # noqa: E402

CORPUS_PATH = Path(__file__).resolve().parent / "fixtures" / "secrets_corpus.jsonl"
MIN_RECALL = 0.95
MAX_FPR = 0.02
MIN_BARE_NON_GENERIC_RECALL = 0.90
_GENERIC_RULE_IDS = frozenset(
    {"generic-api-key", "local-high-entropy-alnum", "local-high-entropy-b64"}
)


def _load_corpus() -> list[dict[str, object]]:
    rows = []
    with CORPUS_PATH.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def test_redaction_gate_recall_and_false_positive_rate() -> None:
    rows = _load_corpus()
    positives = [r for r in rows if r["secret"] is not None]
    negatives = [r for r in rows if r["secret"] is None]
    assert len(positives) >= 150, "expected at least 150 positives in the corpus"
    assert len(negatives) >= 150, "expected at least 150 hard negatives in the corpus"

    family_total: Counter[str] = Counter()
    family_hit: Counter[str] = Counter()
    bare_total: Counter[str] = Counter()
    bare_non_generic_hit: Counter[str] = Counter()
    recalled = 0
    for row in positives:
        text = str(row["text"])
        secret = str(row["secret"])
        family = str(row["family"])
        is_bare = bool(row["bare"])
        cleaned, rule_ids = redact.redact_detail(text)
        family_total[family] += 1
        if secret not in cleaned:
            recalled += 1
            family_hit[family] += 1
        if is_bare and family in STRUCTURED_FAMILIES:
            bare_total[family] += 1
            non_generic_hit = any(r not in _GENERIC_RULE_IDS for r in rule_ids)
            if non_generic_hit:
                bare_non_generic_hit[family] += 1
    recall = recalled / len(positives)

    false_positives = 0
    negative_family_total: Counter[str] = Counter()
    negative_family_fp: Counter[str] = Counter()
    for row in negatives:
        text = str(row["text"])
        family = str(row["family"])
        _cleaned, hits = redact.redact(text)
        negative_family_total[family] += 1
        if hits > 0:
            false_positives += 1
            negative_family_fp[family] += 1
    fpr = false_positives / len(negatives)

    print(f"G1.7 recall={recall:.4f} ({recalled}/{len(positives)})")
    print(f"G1.7 fpr={fpr:.4f} ({false_positives}/{len(negatives)})")
    print("per-family recall:")
    for family in sorted(family_total):
        total = family_total[family]
        hit = family_hit[family]
        print(f"  {family}: {hit}/{total} = {hit / total:.3f}")
    print("per-negative-category FPR:")
    for family in sorted(negative_family_total):
        total = negative_family_total[family]
        fp = negative_family_fp[family]
        print(f"  {family}: {fp}/{total} = {fp / total:.3f}")
    print("bare-context non-generic recall (structured families):")
    bare_recall_table: dict[str, tuple[int, int]] = {}
    for family in STRUCTURED_FAMILIES:
        total = bare_total[family]
        hit = bare_non_generic_hit[family]
        bare_recall_table[family] = (hit, total)
        rate = hit / total if total else float("nan")
        print(f"  {family}: {hit}/{total} = {rate:.3f}")

    assert recall >= MIN_RECALL, (
        f"recall {recall:.4f} below {MIN_RECALL}; per-family: "
        f"{ {f: (family_hit[f], family_total[f]) for f in sorted(family_total)} }"
    )
    negative_table = {
        f: (negative_family_fp[f], negative_family_total[f]) for f in sorted(negative_family_total)
    }
    assert fpr <= MAX_FPR, (
        f"false-positive rate {fpr:.4f} above {MAX_FPR}; per-category: {negative_table}"
    )
    misses = {
        family: (hit, total)
        for family, (hit, total) in bare_recall_table.items()
        if total and hit / total < MIN_BARE_NON_GENERIC_RECALL
    }
    assert not misses, (
        f"bare-context non-generic recall below {MIN_BARE_NON_GENERIC_RECALL} for: {misses}"
    )


def test_redact_detail_exposes_firing_rule_ids() -> None:
    text = "export OPENAI_API_KEY=sk-abcdefghijklmnopqrstT3BlbkFJabcdefghijklmnopqrst"
    cleaned, rule_ids = redact.redact_detail(text)
    assert rule_ids
    assert all(isinstance(r, str) for r in rule_ids)
    assert "[REDACTED:" in cleaned


def test_bare_context_family_counts_are_nonzero() -> None:
    """Sanity check that the corpus actually contains bare positives per family
    (a zero-total family would make the gate's bare assertion vacuous)."""
    rows = _load_corpus()
    bare_family_counts: dict[str, int] = defaultdict(int)
    for row in rows:
        if row["secret"] is not None and row["bare"]:
            bare_family_counts[str(row["family"])] += 1
    for family in STRUCTURED_FAMILIES:
        assert bare_family_counts.get(family, 0) >= 4, (
            f"{family} has too few bare positives to measure bare recall"
        )
