"""Gate G1.7 (task-2-brief.md): redaction recall and false-positive rate.

Recall = fraction of positives whose `secret` no longer appears verbatim in
the redacted output. False-positive rate = fraction of negatives (secret is
null) that get any hit at all. The corpus (tests/fixtures/secrets_corpus.jsonl)
is generated by `python3 scripts/gen_redact.py --corpus`
(scripts/gen_corpus.py) and must never be hand-tuned to make these numbers
look better than they are.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "plugin" / "hooks"))
from verdict_hot import redact  # noqa: E402

CORPUS_PATH = Path(__file__).resolve().parent / "fixtures" / "secrets_corpus.jsonl"
MIN_RECALL = 0.95
MAX_FPR = 0.02


def _load_corpus() -> list[dict[str, object]]:
    rows = []
    with CORPUS_PATH.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def test_redaction_gate_recall_and_false_positive_rate() -> None:
    rows = _load_corpus()
    positives = [r for r in rows if r["secret"] is not None]
    negatives = [r for r in rows if r["secret"] is None]
    assert len(positives) >= 150, "expected roughly 200 positives in the corpus"
    assert len(negatives) >= 150, "expected roughly 200 hard negatives in the corpus"

    family_total: Counter[str] = Counter()
    family_hit: Counter[str] = Counter()
    recalled = 0
    for row in positives:
        text = str(row["text"])
        secret = str(row["secret"])
        family = str(row["family"])
        cleaned, _hits = redact.redact(text)
        family_total[family] += 1
        if secret not in cleaned:
            recalled += 1
            family_hit[family] += 1
    recall = recalled / len(positives)

    false_positives = 0
    for row in negatives:
        text = str(row["text"])
        _cleaned, hits = redact.redact(text)
        if hits > 0:
            false_positives += 1
    fpr = false_positives / len(negatives)

    print(f"G1.7 recall={recall:.4f} ({recalled}/{len(positives)})")
    print(f"G1.7 fpr={fpr:.4f} ({false_positives}/{len(negatives)})")
    print("per-family recall:")
    for family in sorted(family_total):
        total = family_total[family]
        hit = family_hit[family]
        print(f"  {family}: {hit}/{total} = {hit / total:.3f}")

    assert recall >= MIN_RECALL, (
        f"recall {recall:.4f} below {MIN_RECALL}; per-family: "
        f"{ {f: (family_hit[f], family_total[f]) for f in sorted(family_total)} }"
    )
    assert fpr <= MAX_FPR, f"false-positive rate {fpr:.4f} above {MAX_FPR}"
